In [1]:
!pip install --upgrade pytube youtube-comment-downloader pandas

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.5/315.5 kB 11.5 MB/s eta 0:00:00
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.


In [2]:
!pip install youtube-comment-downloader
!pip install youtube-search-python

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.5/99.5 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.1/89.1 kB 6.0 MB/s eta 0:00:00


In [7]:
# Import library yang dibutuhkan
import pandas as pd
from youtube_comment_downloader import YoutubeCommentDownloader
from pytube import Search  # Menggunakan Pytube untuk pencarian
import itertools

# 1. Masukkan KATA KUNCI yang ingin Anda cari di YouTube
KATA_KUNCI_PENCARIAN = "ulasan Toyota Vios 2023 Indonesia"

# 2. Tentukan berapa video teratas dari hasil pencarian yang ingin di-scrape
JUMLAH_VIDEO_UNTUK_DISCRAPE = 10 # Ambil video teratas

# 3. Batasi jumlah maksimal komentar yang diambil PER VIDEO
MAKSIMAL_KOMENTAR_PER_VIDEO = 200 # Ambil komentar dari setiap video

# 4. Tentukan nama file output untuk menyimpan SEMUA komentar
NAMA_FILE_OUTPUT = 'scraping_vios_1000.csv'

# -----------------------------------------------------
# --- PROSES SCRAPING OTOMATIS  ---
# -----------------------------------------------------

print(f"Mencari video di YouTube dengan kata kunci: '{KATA_KUNCI_PENCARIAN}'...")

# TAHAP 1: MENCARI VIDEO MENGGUNAKAN PYTUBE
try:
    s = Search(KATA_KUNCI_PENCARIAN)
    list_url_video = []
    # Ambil URL video sebanyak JUMLAH_VIDEO_UNTUK_DISCRAPE
    for i, video in enumerate(s.results):
        if i >= JUMLAH_VIDEO_UNTUK_DISCRAPE:
            break
        list_url_video.append(video.watch_url)
except Exception as e:
    print(f"Gagal melakukan pencarian video. Error: {e}")
    list_url_video = []


if not list_url_video:
    print("Tidak ada video yang ditemukan dengan kata kunci tersebut.")
else:
    print(f"Berhasil menemukan {len(list_url_video)} video. Memulai proses scraping komentar...")

    semua_komentar_total = []
    downloader = YoutubeCommentDownloader()

    # TAHAP 2: SCRAPING KOMENTAR DARI SETIAP VIDEO (Tetap sama)
    for i, url in enumerate(list_url_video):
        print(f"\n({i+1}/{len(list_url_video)}) Scraping dari URL: {url}")
        try:
            komentar_generator = downloader.get_comments_from_url(url, sort_by=1)
            for comment in itertools.islice(komentar_generator, MAKSIMAL_KOMENTAR_PER_VIDEO):
                data_komentar = {
                    'username': comment.get('author'),
                    'waktu': comment.get('time'),
                    'teks_komentar': comment.get('text'),
                    'jumlah_likes': comment.get('votes', 0),
                    'sumber_video': url
                }
                semua_komentar_total.append(data_komentar)
            print(f"  -> Selesai. Berhasil mengambil komentar dari video ini.")
        except Exception as e:
            print(f"  -> Gagal mengambil komentar dari video ini. Error: {e}")
            continue

    # TAHAP 3: MENYIMPAN HASIL GABUNGAN (Tetap sama)
    if semua_komentar_total:
        df_gabungan = pd.DataFrame(semua_komentar_total)
        df_gabungan.to_csv(NAMA_FILE_OUTPUT, index=False)
        print(f"\n✅ PROSES SELESEI! Total {len(df_gabungan)} komentar dari {len(list_url_video)} video telah disimpan ke '{NAMA_FILE_OUTPUT}'")
    else:
        print("\nTidak ada komentar yang berhasil di-scrape.")

Mencari video di YouTube dengan kata kunci: 'ulasan Toyota Vios 2023 Indonesia'...


Berhasil menemukan 10 video. Memulai proses scraping komentar...

(1/10) Scraping dari URL: https://youtube.com/watch?v=HR4ELY1Xm3w
  -> Selesai. Berhasil mengambil komentar dari video ini.

(2/10) Scraping dari URL: https://youtube.com/watch?v=yeEoWUXHf54
  -> Selesai. Berhasil mengambil komentar dari video ini.

(3/10) Scraping dari URL: https://youtube.com/watch?v=YdTPa-zESgM
  -> Selesai. Berhasil mengambil komentar dari video ini.

(4/10) Scraping dari URL: https://youtube.com/watch?v=FDU3zV2_n04
  -> Selesai. Berhasil mengambil komentar dari video ini.

(5/10) Scraping dari URL: https://youtube.com/watch?v=dCynfd001QM
  -> Selesai. Berhasil mengambil komentar dari video ini.

(6/10) Scraping dari URL: https://youtube.com/watch?v=JbxzblT3my4
  -> Selesai. Berhasil mengambil komentar dari video ini.

(7/10) Scraping dari URL: https://youtube.com/watch?v=iiJQ6kbxZLI
  -> Selesai. Berhasil mengambil komentar dari video ini.

(8/10) Scraping dari URL: https://youtube.com/watch?v=J90xY

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from google.colab import files
import io

# upload file
uploaded = files.upload()

# Cek nama file yang terupload
filenames = list(uploaded.keys())
print(f"\nFile yang terupload: {filenames}")

=== LANGKAH 1: UPLOAD DATA ===


Saving hasil_labelling_vios.csv to hasil_labelling_vios.csv
Saving scraping_vios_1000.csv to scraping_vios_1000.csv

File yang terupload: ['hasil_labelling_vios.csv', 'scraping_vios_1000.csv']


In [3]:
# Konfigurasi Nama File (Sesuaikan jika nama file upload berbeda)
FILE_MANUAL = 'hasil_labelling_vios.csv'
FILE_RAW = 'scraping_vios_1000.csv'

In [4]:
# [cite_start]Load Data Manual (Labeled) [cite: 236]
df_train = pd.read_csv(io.BytesIO(uploaded[FILE_MANUAL]))

df_raw = pd.read_csv(io.BytesIO(uploaded[FILE_RAW]))

print(f"Data Manual : {len(df_train)} baris")
print(f"Data Raw : {len(df_raw)} baris")

Data Manual : 279 baris
Data Raw : 1141 baris


In [6]:
# 1. Samakan kolom teks menjadi 'final_text'
if 'text' in df_train.columns:
  df_train.rename(columns={'text': 'final_text'}, inplace=True)
if 'teks_komentar' in df_raw.columns:
  df_raw.rename(columns={'teks_komentar': 'final_text'}, inplace=True)

# 2. Samakan kolom subjek/username
if 'username' in df_raw.columns:
  df_raw.rename(columns={'username': 'subjek'}, inplace=True)
if 'subjek' not in df_train.columns:
  df_train['subjek'] = 'manual_labeler'  # Default untuk data manual

# 3. Pastikan format string & bersihkan NaN
df_train['final_text'] = df_train['final_text'].astype(str).fillna('')
df_raw['final_text'] = df_raw['final_text'].astype(str).fillna('')

#4. Hapus baris di data training yang labelnya kosong (jika ada)
df_train = df_train.dropna(subset=['label'])

print("\n[Info] Kolom berhasil disesuaikan menjadi 'final_text' dan 'subjek'.")
print(df_train[['final_text', 'label']].head(3))


[Info] Kolom berhasil disesuaikan menjadi 'final_text' dan 'subjek'.
                                          final_text    label
0    Toyota Vios Gen 4:\n🤫ssssssttt!!!! (suara diam)  positif
1  Vios adalah versi sedan dari Veloz krn dasborn...  positif
2  Radius putarnya masih boros gak ya...kayak vio...  negatif


In [7]:
# Inisialisasi TF-IDF (menangkap unigram dan bigram)
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1, 2))

# Fit pada data training manual
X_train_vec = tfidf.fit_transform(df_train['final_text'])
y_train = df_train['label']

print(f"[OK] Vektorisasi selesai. Ukuran matriks: {X_train_vec.shape}")

[OK] Vektorisasi selesai. Ukuran matriks: (279, 3268)


In [8]:
print("=== LANGKAH 4: TRAINING & EVALUASI ===")

# Split data 80:20 untuk testing internal
X_tr, X_ts, y_tr, y_ts = train_test_split(
    X_train_vec, y_train, test_size=0.2, random_state=42, stratify=y_train
)

# Latih Model SVM
model = SVC(kernel='linear', probability=True, random_state=42)
model.fit(X_tr, y_tr)

# Prediksi untuk evaluasi
y_pred = model.predict(X_ts)
acc = accuracy_score(y_ts, y_pred)

print(f"\n>> AKURASI MODEL PADA DATA TEST: {acc*100:.2f}%")
print("-" * 50)
print(classification_report(y_ts, y_pred))
print("-" * 50)
print("Confusion Matrix:")
print(confusion_matrix(y_ts, y_pred))

# Training Ulang dengan FULL Data Manual untuk hasil maksimal
print("\n[Training] Melatih ulang model dengan 100% data manual...")
model_final = SVC(kernel='linear', probability=True, random_state=42)
model_final.fit(X_train_vec, y_train)

=== LANGKAH 4: TRAINING & EVALUASI ===

>> AKURASI MODEL PADA DATA TEST: 58.93%
--------------------------------------------------
              precision    recall  f1-score   support

     negatif       0.59      0.80      0.68        20
      netral       0.50      0.25      0.33        16
     positif       0.62      0.65      0.63        20

    accuracy                           0.59        56
   macro avg       0.57      0.57      0.55        56
weighted avg       0.58      0.59      0.56        56

--------------------------------------------------
Confusion Matrix:
[[16  3  1]
 [ 5  4  7]
 [ 6  1 13]]

[Training] Melatih ulang model dengan 100% data manual...


SVC(kernel='linear', probability=True, random_state=42)

In [9]:
print("=== LANGKAH 5: PREDIKSI DATA UNLABELED ===")

# 1. Identifikasi Data yang Belum Dilabeli (Anti-Leakage)
# Kita gunakan teks sebagai kunci unik (lowercase & strip whitespace)
df_train['key'] = df_train['final_text'].str.strip().str.lower()
df_raw['key'] = df_raw['final_text'].str.strip().str.lower()

# Ambil data RAW yang kuncinya TIDAK ADA di TRAINING MANUAL
labeled_keys = set(df_train['key'])
df_unlabeled = df_raw[~df_raw['key'].isin(labeled_keys)].copy()

print(f"Total Data Raw: {len(df_raw)}")
print(f"Total Data Manual: {len(df_train)}")
print(f"Data Sisa (Unlabeled) yang akan diprediksi: {len(df_unlabeled)}")

# 2. Lakukan Prediksi
if len(df_unlabeled) > 0:
    X_unlabeled = tfidf.transform(df_unlabeled['final_text'])

    # Prediksi Label & Probabilitas
    preds = model_final.predict(X_unlabeled)
    probs = model_final.predict_proba(X_unlabeled)
    confidence = np.max(probs, axis=1) # Ambil nilai probabilitas tertinggi

    # Simpan ke DataFrame
    df_unlabeled['label'] = preds
    df_unlabeled['status'] = 'prediksi_model'
    df_unlabeled['confidence'] = confidence

    print("\nContoh Hasil Prediksi AI:")
    print(df_unlabeled[['final_text', 'label', 'confidence']].head())
else:
    print("Semua data raw ternyata sudah ada di file manual. Tidak ada yang perlu diprediksi.")

=== LANGKAH 5: PREDIKSI DATA UNLABELED ===
Total Data Raw: 1141
Total Data Manual: 279
Data Sisa (Unlabeled) yang akan diprediksi: 857

Contoh Hasil Prediksi AI:
                                           final_text    label  confidence
1   Keren sih di harga Rp300jt-an sudah dapat mobi...  positif    0.487609
5   Mudah-mudahan harga jual Daihatsu juga tinggi ...  negatif    0.881384
8   Gw udah pake tapi si Om nya nge review banyaka...  positif    0.577409
9        Vios bukan bikin Daihatsu min,,,tapi Assb...  positif    0.729046
11  Latihan ngmong dlu bos. Bngung gw nangkep suar...  positif    0.807555


In [10]:
print("=== LANGKAH 6: SIMPAN & DOWNLOAD ===")

# Set status data manual
df_train['status'] = 'manual'
df_train['confidence'] = 1.0

# Kolom yang akan disimpan
cols = ['subjek', 'final_text', 'label', 'status', 'confidence']

# Pastikan kolom tersedia di df_unlabeled (jika ada kolom missing)
for col in cols:
    if col not in df_unlabeled.columns:
        df_unlabeled[col] = None

# Gabungkan
df_final = pd.concat([df_train[cols], df_unlabeled[cols]], ignore_index=True)

# Simpan CSV
output_filename = 'dataset_self_train.csv'
df_final.to_csv(output_filename, index=False)

print(f"File berhasil dibuat: {output_filename}")
print(f"Total baris data akhir: {len(df_final)}")

# Trigger Download
files.download(output_filename)

=== LANGKAH 6: SIMPAN & DOWNLOAD ===
File berhasil dibuat: dataset_self_train.csv
Total baris data akhir: 1136


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>